import Link from "next/link";
import { and, count, eq, sql } from "drizzle-orm";

import { AdminGuard } from "@/components/admin/admin-guard";
import { HowTo } from "@/components/admin/how-to";
import { PageHeader } from "@/components/admin/page-header";
import { db, schema } from "@/lib/db";

/**
 * Billing.
 *
 * The page used to list USSD sessions with phone numbers, amounts and statuses,
 * all generated by `lib/mock/ussd`, so an operator was reading invented payment
 * activity. That was replaced by a "Coming soon" screen, which was honest and
 * also a door to a wall: the entry sat in the sidebar and led nowhere.
 *
 * Money does move through this platform, just not through this page. So it says
 * where it moves, with the real numbers behind it, and says plainly which of
 * the two things the section is named after is not built. Nothing here is a
 * settings form: the processor is chosen by an environment variable on the
 * server, and a switch in the browser that claimed to change it would be the
 * same lie as the USSD table.
 */

export const dynamic = "force-dynamic";

const naira = new Intl.NumberFormat("en-NG", {
  style: "currency",
  currency: "NGN",
  maximumFractionDigits: 0,
});

async function readMoney() {
  const [subs] = await db
    .select({
      n: count(),
      value: sql<number>`coalesce(sum(${schema.subscriptions.priceNgn}), 0)`,
    })
    .from(schema.subscriptions)
    .where(eq(schema.subscriptions.status, "active"));

  const [orders] = await db
    .select({
      n: count(),
      value: sql<number>`coalesce(sum(${schema.orders.totalNgn}), 0)`,
    })
    .from(schema.orders)
    .where(eq(schema.orders.status, "paid"));

  const [refunded] = await db
    .select({ n: count() })
    .from(schema.orders)
    .where(eq(schema.orders.status, "refunded"));

  return {
    activeSubs: Number(subs?.n ?? 0),
    subsValueNgn: Number(subs?.value ?? 0),
    paidOrders: Number(orders?.n ?? 0),
    ordersValueNgn: Number(orders?.value ?? 0),
    refundedOrders: Number(refunded?.n ?? 0),
  };
}

export default async function AdminBillingRoute() {
  return (
    <div className="p-6 lg:p-8">
      <AdminGuard capability="commerce">
        {/* The read happens inside the guard, so a role that cannot open the
            section never causes the query to run. */}
        <BillingBody />
      </AdminGuard>
    </div>
  );
}

async function BillingBody() {
  const money = await readMoney();
  // Named on the server. A browser cannot be trusted to say which processor is
  // taking money, and the answer is one environment variable.
  const provider = process.env.PAYMENT_PROVIDER ?? "unset";
  const takingRealMoney = provider === "paystack";

  return (
    <div className="space-y-6">
      <PageHeader
        title="Billing"
        description="Where money comes in, and what is not wired up yet."
      />
      <HowTo page="billing" />

      {!takingRealMoney ? (
        <p className="rounded-xl bg-amber-500/15 p-4 text-sm text-amber-100">
          The payment processor is set to <strong>{provider}</strong>, not
          Paystack. Checkout refuses to run in production with anything else, so
          nobody can buy anything until this is corrected on the server.
        </p>
      ) : null}

      <div className="grid gap-4 sm:grid-cols-2">
        <Panel
          href="/admin/subscriptions"
          title="Subscriptions"
          lead={`${money.activeSubs} active`}
          value={naira.format(money.subsValueNgn)}
          note="What the active periods are worth at the price each was bought on. Access to premium content is read from these rows, not from a role."
        />
        <Panel
          href="/admin/orders"
          title="Shop orders"
          lead={`${money.paidOrders} paid`}
          value={naira.format(money.ordersValueNgn)}
          note={
            money.refundedOrders > 0
              ? `${money.refundedOrders} refunded, which is not counted above.`
              : "Nothing refunded. Refunds go back through Paystack and are marked on the order."
          }
        />
      </div>

      <section className="rounded-xl bg-card/60 p-5">
        <h2 className="text-sm font-semibold text-foreground">
          Cards, through Paystack
        </h2>
        <p className="mt-1 max-w-[70ch] text-sm text-muted-foreground">
          Every subscription and every shop order is charged by Paystack, in
          naira, and settled to the account configured there. The processor is
          set on the server rather than here: a switch in the browser could put
          the platform into a mode where payments are approved without money
          moving, which is exactly the bug that shipped on 16 August.
        </p>
      </section>

      <section className="rounded-xl bg-card/60 p-5">
        <h2 className="text-sm font-semibold text-foreground">
          USSD, not integrated
        </h2>
        <p className="mt-1 max-w-[70ch] text-sm text-muted-foreground">
          There is no short code, no aggregator agreement and no table behind
          one, so a viewer on a feature phone cannot pay yet. Wiring it needs a
          short code from an aggregator, a callback route that takes their
          session steps, and the same subscription write the card path already
          does. Until that exists this page says so rather than showing a list
          of sessions nobody can act on.
        </p>
      </section>
    </div>
  );
}

function Panel({
  href,
  title,
  lead,
  value,
  note,
}: {
  href: string;
  title: string;
  lead: string;
  value: string;
  note: string;
}) {
  return (
    <Link
      href={href}
      className="block rounded-xl bg-card/60 p-5 transition-colors hover:bg-card"
    >
      <p className="text-sm font-semibold text-foreground">{title}</p>
      <p className="mt-2 text-2xl font-semibold tabular-nums text-foreground">
        {value}
      </p>
      <p className="text-xs text-muted-foreground">{lead}</p>
      <p className="mt-3 max-w-[46ch] text-xs text-muted-foreground">{note}</p>
    </Link>
  );
}
