import { AdminGuard } from "@/components/admin/admin-guard";
import { ComingSoon } from "@/components/shell/coming-soon";

/**
 * Billing and USSD.
 *
 * The page listed USSD sessions with phone numbers, amounts and statuses, all
 * generated by `lib/mock/ussd`. There is no USSD integration and no table behind
 * it, so an operator was reading invented payment activity. Subscriptions and
 * Paystack orders are real and live under Orders; USSD is not built.
 */
export default function AdminBillingRoute() {
  return (
    <div className="p-6 lg:p-8">
      <AdminGuard capability="commerce">
        <ComingSoon
          title="Billing and USSD"
          description="USSD payments are not integrated yet. Paystack orders are under Orders."
        />
      </AdminGuard>
    </div>
  );
}
